### ISSUE TITLE
feat: add a flag to enforce CORS security check

### ISSUE THREAD

**Issue by fredvdv** [vdbulcke/oidc-client-demo#26]
# Description

add a flag to enforce CORS acting like a web browser when fetching well-known openid-configuration

# Configuration

```yaml
## Override config
enforce_cors: true
```

# Implementation

Send an `OPTION` call before getting the well-known openid-configuration and check the CORS headers

**Comment by vdbulcke** [comment]
It is better to created a separate project with a OIDC SPA (e.g. https://github.com/curityio/pkce-javascript-example)
